---
- name: test
  file: path=/tmp/foo.conf  mode=0644 state=touch
- name: install python
  become: true
  apt: 
    name: software-properties-common
    state: latest
- name: Apt-get update
  apt:
   name: "*"
   update_cache: yes
   state: latest

- name: Installing MariaDB Galera packages
  apt: name={{item}} state=present 
  with_items:
      - mariadb-common
      - mariadb-client
      - mariadb-server
      
- name: start sql service and enable the service
  service: name=mysql state=started enabled=yes

- name: install python mysql bindings
  apt: name=python-mysqldb state=present
  become: yes
  become_method: sudo


- name: set the sql root password
  mysql_user: 
    name: root
    password: "{{ root_password }}"
    host: localhost

- name: copy .my.cnf file with root password credentials
  template: src=files/my-cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: set the sql debian-sys-maint password
  mysql_user: user=debian-sys-maint
              password="{{ debian_sys_maint_password }}"
              host=localhost
- name: delete anonymous sql server user for localhost
  mysql_user: user=""
              state="absent"
- name: Stop mysql services
  service: name=mysql state=stopped
  ignore_errors: yes 

- name: Bootstrap mysql service
  service: name=mysql state=started args='--wsrep-new-cluster'
  when: play_hosts[0] == inventory_hostname

- name: Start mysql in other nodes
  service: name=mysql state=restarted 
  when: play_hosts[0] != inventory_hostname

- name: Restart mysql on first node
  service: name=mysql state=restarted
  when: play_hosts[0] == inventory_hostname

